services:

  # Data Generation Service
  random_data_generator:
    build: ./random_data_generator
    container_name: random_data_generator
    depends_on:
      - kafka
    networks:
      - sparknet

  # Data Processing Service
  
  #Master
  spark-master:
    build: ./manager
    container_name: spark-master
    ports:
      - "7077:7077"
      - "8081:8080"  
    environment:
      - SPARK_MODE=master
    networks:
      - sparknet

# Driver / Application
  worker_etl:
    build: ./worker_etl
    container_name: worker_etl
    depends_on:
      - kafka
      - final_storage_db
      - spark-master
    networks:
      - sparknet
  # Workers
  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - sparknet

  # KAKFA CONFIGURATION
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - sparknet
  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    env_file:
      - ./kafka/.env_kafka
    depends_on:
      - zookeeper
    networks:
      - sparknet

  kafka-init:
    image: bitnami/kafka:3.6
    container_name: kafka-init
    depends_on:
      - kafka
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        sleep 10 &&
        kafka-topics.sh --create \
          --if-not-exists \
          --bootstrap-server kafka:9092 \
          --replication-factor 1 \
          --partitions 3 \
          --topic raw-events
    networks:
      - sparknet

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - kafka
    networks:
      - sparknet
      
  # DB CONFIGURATION
  final_storage_db:
    image: postgres
    container_name: final_storage_db
    env_file:
      - ./final_storage_db/.env
    ports:
      - "5432:5432"
    volumes:
      - final_storage:/var/lib/postgresql/data
      - ./final_storage_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sparknet

networks:
  sparknet:
    driver: bridge

volumes:
  final_storage:
